# Generated by Django 2.2.5 on 2020-01-20 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.URLField()),
                ('victorias', models.PositiveIntegerField()),
                ('derrotas', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id_mercado', models.AutoField(primary_key=True, serialize=False)),
                ('ultima_fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id_mercado',),
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.URLField()),
                ('posicion', models.CharField(choices=[('PT', 'Portero'), ('DF', 'Defensa'), ('MC', 'Mediocentro'), ('DL', 'Delantero')], max_length=50)),
                ('forma', models.CharField(max_length=50)),
                ('ultimos_puntos', models.TextField(max_length=200)),
                ('puntos_totales', models.IntegerField()),
                ('valor_mercado', models.IntegerField(validators=[django.core.validators.MinValueValidator(150000)])),
                ('partidos_jugados', models.PositiveIntegerField()),
                ('goles', models.PositiveIntegerField()),
                ('tarjetas', models.PositiveIntegerField()),
                ('media_puntos', models.FloatField()),
                ('id_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiKlopp.Equipo')),
                ('id_mercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiKlopp.Mercado')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
