# Generated by Django 2.2.5 on 2020-01-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiKlopp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiEquipo',
            fields=[
                ('id_mi_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ultima_fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='id_mi_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BiKlopp.MiEquipo'),
        ),
    ]
